hz/cart/urls.py
from django.urls import path
from .views import *

app_name = 'cart'

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', cart_add, name='cart_add'),
    path('remove/<int:product_id>/', cart_remove, name='cart_remove'),
]

hz/hz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about_us/', include('about_us.urls')),
    path('user/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('', include('baton.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hz/cart/models.py
from django.db import models

hz/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    """Форма кол-ва и изменения кол-ва товара"""
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        label='Кол-во'
    )
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput(attrs={'class': 'nice-select'})
    )

hz/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from baton.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    """Добавление товара в корзину"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    """Удаление товара из корзины"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    """Изменение/обновление кол-ва товара в корзине"""
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'update': True,
        })
    return render(request, 'cart/detail.html', {'cart': cart})

hz/cart/templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Корзина{% endblock %}

{% block content %}

<!-- cart -->
<div class="cart-section mt-150 mb-150">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="cart-table-wrap">
                    <table class="cart-table">
                        <thead class="cart-table-head">
                        <tr class="table-head-row">
                            <th class="product-remove"></th>
                            <th class="product-image"></th>
                            <th class="product-name">Товар</th>
                            <th class="product-price">Цена</th>
                            <th class="product-quantity">Обновить кол-во</th>
                            <th class="product-total">кол-во</th>
                            <th class="product-price">Сумма</th>
                            <th class="product-total">Всего</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in cart %}
                        {% with product=item.product %}
                        <tr class="table-body-row">
                            <td class="product-remove"><a href="{% url 'cart:cart_remove' product.id %}"><i class="far fa-window-close"></i></a></td>
                            <td class="product-image"><img src="{{ product.photo.url }}" alt="фото товара"></td>
                            <td class="product-name">{{ product.title }}</td>
                            <td class="product-price">{{ product.price }}</td>
                            <td>
                                <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.update }}
                                    <input type="submit" style="width: 100px; height: 30px; " value="Обновить">
                                    {% csrf_token %}
                                </form>
                            </td>
                            <td class="product-total">{{ item.quantity }}</td>
                            <th class="product-price">{{ item.total_price }}</th>
                            {% endwith %}
                            {% endfor %}
                            <th class="product-price">{{ cart.get_total_price }}</th>
                        </tbody>
                    </table>
                    <div align="right"><a href="#" class="cart-btn">Оформить заказ</a> </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end cart -->

<!-- cart button -->
	<div class="more-products mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="section-title">
						<div class="text-bg">
							<div align="center"><a href="{% url 'shop' %}">Вернуться в магазин</a></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- end cart button -->







{% endblock%}